server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:

          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                exposedHeaders:
                  - Authorization
                allowCredentials: true

          routes:
            - id: auth-service-auth-route
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**

            - id: auth-service-admin-route
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/admin/**

            - id: auth-service-test-route
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/test/**

            - id: workspace-service-route
              uri: lb://WORKSPACE-SERVICE
              predicates:
                - Path=/api/v1/workspaces/**

            - id: resource-service-route
              uri: lb://RESOURCE-SERVICE
              predicates:
                - Path=/api/v1/resources/**

            - id: assignment-service-route
              uri: lb://ASSIGNMENT-SERVICE
              predicates:
                - Path=/api/v1/assignments/**

            - id: submission-service-route
              uri: lb://SUBMISSION-SERVICE
              predicates:
                - Path=/api/v1/submissions/**

            - id: leaderboard-service-route
              uri: lb://LEADERBOARD-SERVICE
              predicates:
                - Path=/api/v1/leaderboards/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway

  endpoint:
    health:
      show-details: always

    gateway:
      access: read-only